In [1]:
import numpy as np

In [2]:
data = np.load('monthdata.npz')
totals = data['totals']
counts = data['counts']

In [18]:
lowest_total_precipitation = np.argmin(totals.sum(axis=1))
print("Row with lowest total precipitation:\n",lowest_total_precipitation)

Row with lowest total precipitation:
 8


In [17]:
total_precipitation_month = totals.sum(axis=0)
total_observation_month = counts.sum(axis=0)
print("Average precipitation in each month:\n",total_precipitation_month/total_observation_month)

Average precipitation in each month:
 [27.77978339 30.42629482 29.41007194 17.96654275 21.34456929 20.69498069
 24.97718631 19.85661765 24.06563707 44.68441065 34.61568627 32.36679537]


In [20]:
total_precipitation_daily = totals.sum(axis=1)
total_observation_daily = counts.sum(axis=1)
print("Average precipitation in each city:\n",total_precipitation_daily/total_observation_daily)

Average precipitation in each city:
 [47.77859779 14.33333333 39.91232877 41.44505495 23.4099723  23.68144044
 17.52197802 36.52222222  6.15426997]


In [21]:
print(totals.shape)

(9, 12)


In [22]:
quarter_total = np.reshape(totals, (4*totals.shape[0], 3))

In [25]:
quarter_total_sum = quarter_total.sum(axis=1)

In [26]:
print(quarter_total_sum)

[5450 1408 1466 4624  189 1339 3148  527 3120 3357 3386 4705 4416 3321
 2024 5325 2024 1498 1721 3208 1786 1809 2557 2397 1583 1296 1729 1770
 4602 1340 1250 5956  338  524  922  450]


In [27]:
quarter_total = np.reshape(quarter_total_sum, (totals.shape[0],4))

In [28]:
print(quarter_total)

[[5450 1408 1466 4624]
 [ 189 1339 3148  527]
 [3120 3357 3386 4705]
 [4416 3321 2024 5325]
 [2024 1498 1721 3208]
 [1786 1809 2557 2397]
 [1583 1296 1729 1770]
 [4602 1340 1250 5956]
 [ 338  524  922  450]]
